[project]
name = "regularization-vs-perf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "pyyaml>=6.0.3",
    "seaborn>=0.13.2",
    "typer>=0.19.2",
    "typer-config>=1.4.2",
]
